name: Build Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
      - name: Checkout source code.
        uses: actions/checkout@master
        
      - name: Download ApplicationPorperties
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir src/main/resources;
          aws s3 cp s3://spacedeploy/application.properties src/main/resources
          
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
